version: "3"
services:
  api:
    container_name: api
    image: ghcr.io/teamshackathon/dev/ai-agnet-backend:latest
    volumes: 
      - ./:/app/
    restart: always
    environment:
      - ENVIRONMENT=development
    entrypoint: bash -c "chmod 777 /app/dev_start.sh && bash /app/dev_start.sh"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: postgresql
    image: ghcr.io/longlangu/dev/postgres-pg-vector:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'manabiyaai_development'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  phppgadmin:
    container_name: phppgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
  doc:
    container_name: doc
    image: swaggerapi/swagger-ui:v5.18.2
    volumes:
      - ./doc/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    ports:
      - 9000:8080
volumes:
  db_data:
  pgadmin-data: